name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install Dependencias
      run: |
            cd app
            npm install

    - name: Build Angular App
      run: |
        cd app
        npm run build

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/app-code-warrior/browser  # ajuste o caminho do diretório de construção do seu projeto Angular
