name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feature/*
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repositorio
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install Dependencias
      run: |
            cd app
            npm install

    - name: Build Angular App
      run: |
        cd app
        npm run build

    - name: Create 404 Page Redirect
      run: |
        echo "<!DOCTYPE html>" > app/dist/app-code-warrior/browser/404.html
        echo "<html lang=\"en\">" >> app/dist/app-code-warrior/browser/404.html
        echo "<head>" >> app/dist/app-code-warrior/browser/404.html
        echo "  <meta charset=\"UTF-8\">" >> app/dist/app-code-warrior/browser/404.html
        echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">" >> app/dist/app-code-warrior/browser/404.html
        echo "  <title>Page Not Found</title>" >> app/dist/app-code-warrior/browser/404.html
        echo "</head>" >> app/dist/app-code-warrior/browser/404.html
        echo "<body>" >> app/dist/app-code-warrior/browser/404.html
        echo "  <script>" >> app/dist/app-code-warrior/browser/404.html
        echo "    // Redirect to index.html" >> app/dist/app-code-warrior/browser/404.html
        echo "    window.location.href = 'index.html';" >> app/dist/app-code-warrior/browser/404.html
        echo "  </script>" >> app/dist/app-code-warrior/browser/404.html
        echo "</body>" >> app/dist/app-code-warrior/browser/404.html
        echo "</html>" >> app/dist/app-code-warrior/browser/404.html

    - name: Deploy GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.APP_CODE_WARRIOR }}
        publish_dir: ./app/dist/app-code-warrior/browser